### PR TITLE
Added a cron job to send logs mail to admin

### PR DESCRIPTION
**Pull request by harshit-saraswat**
Issue Resolved:- #12 

Description:
The cron job sends log email in every 1 minute to admin. 

Tasks Done:

- [x] Code Changes
- [x] Background Scheduler Addition

### CODE REVIEW

**Comment by harshit-saraswat** [comment]
Hey @rexdivakar can you please review the PR. To sum it up:
I saw you created a file clock.py which calls a block scheduler for the email cron job. Instead of that I used a background scheduler and now the website works fine. Also to integrate it, I added the scheduler code in the main app.py file.

**Comment by rexdivakar** [comment]
Hey buddy we tried cron but using heroku with CRON jobs had issues, can u try it with parallel execution script ? @harshit-saraswat

**Comment by harshit-saraswat** [comment]
> Hey buddy we tried cron but using heroku with CRON jobs had issues, can u try it with parallel execution script ? @harshit-saraswat

Hey, did you try using it the way I used it in the script? Is it still giving troubles?. Also another thing to do is,using heroku CLI:  
heroku ps:scale clock=1

https://medium.com/@sagarmanohar/using-apscheduler-for-cron-jobs-on-heroku-26fc8cba525a

**Comment by rexdivakar** [comment]
I need to deploy it and verify it @harshit-saraswat  will let u know

**Comment by harshit-saraswat** [comment]
@rexdivakar just changed it to a parallel thread script. Let me know if that's better? You can change the POOL_TIME variable to the number of seconds you want the thread to run after. Currently it's set to 60, which means the thread runs at every 60s to send email.

**Comment by rexdivakar** [comment]
Give me sometime let me check and revert back@harshit-saraswat

**Comment by harshit-saraswat** [comment]
Hey @rexdivakar , did you try it?

**Review by rexdivakar — APPROVED** [review]

**Comment by rexdivakar** [comment]
Great job @harshit-saraswat

**Pull request merged**
